// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview AI agent that suggests personalized promotions to new users based on their location.
 *
 * - suggestPromotions - A function that suggests promotions based on location.
 * - SuggestPromotionsInput - The input type for the suggestPromotions function.
 * - SuggestPromotionsOutput - The return type for the suggestPromotions function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestPromotionsInputSchema = z.object({
  location: z
    .string()
    .describe('The user\u2019s current location to find nearby promotions.'),
});
export type SuggestPromotionsInput = z.infer<typeof SuggestPromotionsInputSchema>;

const SuggestPromotionsOutputSchema = z.object({
  promotions: z
    .array(z.string())
    .describe('A list of personalized promotions based on the user\u2019s location.'),
});
export type SuggestPromotionsOutput = z.infer<typeof SuggestPromotionsOutputSchema>;

export async function suggestPromotions(input: SuggestPromotionsInput): Promise<SuggestPromotionsOutput> {
  return suggestPromotionsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestPromotionsPrompt',
  input: {schema: SuggestPromotionsInputSchema},
  output: {schema: SuggestPromotionsOutputSchema},
  prompt: `You are a marketing expert for Bite Craft, a food delivery service.
  A new user is browsing the website for the first time from the following location: {{{location}}}.
  Suggest 3 relevant promotions that would entice them to place their first order.
  The promotions should be specific to Bite Craft and designed to save the user money.
  Return the promotions as a list of strings.

  For example:
  {
   "promotions": [
    "Free delivery on your first order!",
    "15% off all meals in the {{location}} area!",
    "Buy one get one free on all pizzas!"
   ]
  }
  `,
});

const suggestPromotionsFlow = ai.defineFlow(
  {
    name: 'suggestPromotionsFlow',
    inputSchema: SuggestPromotionsInputSchema,
    outputSchema: SuggestPromotionsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
