
'use client';

// This file is used to explicitly import lucide-react icons,
// which helps with tree-shaking and reduces the initial bundle size.

export {
    Activity,
    CreditCard,
    DollarSign,
    LayoutDashboard,
    LineChart,
    LogOut,
    Package,
    ShoppingBag,
    Users,
    Utensils,
    UtensilsCrossed,
    ShoppingCart,
    Search,
    LayoutGrid,
    List,
    PlusCircle,
    Plus,
    Minus,
    Trash2,
    X,
    Sparkles,
    Loader2,
    Tag,
    CheckCircle2,
    Phone,
    Mail,
    MapPin,
    Moon,
    Sun,
    PanelLeft,
    Check,
    ChevronDown,
    ChevronRight,
    Circle,
    ChevronLeft,
    ChevronUp,
    Truck,
    PersonStanding,
    Settings,
    MoreHorizontal,
    Pencil,
    Eye,
    EyeOff,
    Menu,
    Download,
    ChefHat,
    ArrowRight,
    User as UserIcon,
    MessageSquare,
    Star,
    MailOpen,
} from 'lucide-react';
